<?php


namespace common\models;


use yii\db\Query;
use yii\web\UploadedFile;

/**
 * Class ProfileForm
 * @package common\models
 * @var $user User
 * @var $avatarFile UploadedFile
 */
class ProfileForm extends \yii\base\Model
{
    public $username;
    public $avatar;
    public $avatarFile;
    public $status;
    public $description;
    public $user;

    public function rules()
    {
        return [

            [['username', 'status', 'description'], 'trim'],
            ['username', 'required'],
            ['username',
                'unique',
                'targetClass' => User::class,
                'message' => 'This username has already been taken.',
                'filter' => ['!=', 'username', $this->user->username],
            ],
            ['username', 'string', 'min' => 2, 'max' => 255],
            [['status', 'description'], 'string', 'max' => 255],
            ['avatarFile', 'image', 'extensions' => ['png', 'jpg'], 'minWidth' => 300, 'minHeight' => 300, 'maxSize' => 1024*1024*2],// Max Size 2MB
        ];
    }

    /**
     * Fill the params with data from the user
     *
     * @param User $user
     * @return static
     */
    public function loadFromUser(User $user)
    {
        $this->user = $user;
        $this->username = $user->username;
        $this->status = $user->profile->status;
        $this->description = $user->profile->description;
        $this->avatar = $user->profile->avatar;
    }

    /**
     * $this->user will be the currently logged in user by default
     */
    function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->user = \Yii::$app->user->identity;
    }

    /**
     * Saving data in the user and profile tables
     *
     * @return bool
     */
    public function save()
    {
        if ($this->validate()) {
            $this->user->username = $this->username;
            $profile = $this->user->profile;
            $profile->description = $this->description;
            $profile->status = $this->status;
            (! is_null($this->avatarFile)) && $this->upload();
            if ($this->user->validate() && $profile->validate())
                return $this->user->save() && $profile->save();
        }
        return false;
    }

    /**
     * Uploading avatar file,
     */
    protected function upload()
    {
            $filename = $this->user->id . '.' . $this->avatarFile->extension;
            if ($filename !== $this->user->profile->avatar) {
                $this->user->profile->removeAvatarFile();
            }
            $this->avatarFile->saveAs(\Yii::getAlias('@avatarsLocalPath') . '/' . $filename);
            $this->user->profile->avatar = \Yii::getAlias('@avatarsWebPath') . '/' . $filename;
    }

    /**
     * @return array
     */
    public function attributeLabels()
    {
        return array_merge(parent::attributeLabels(),
        [
          'avatar' => 'Profile Photo'
        ]);
    }





}